“Run: 37”
RunStart
  0%|          | 0/100 [00:00<?, ?it/s]Generation:   0%|          | 0/100 [00:00<?, ?it/s]Generation:   1%|          | 1/100 [00:42<1:10:25, 42.68s/it]Generation:   2%|▏         | 2/100 [01:01<46:59, 28.77s/it]  Generation:   3%|▎         | 3/100 [01:20<39:02, 24.15s/it]Generation:   4%|▍         | 4/100 [01:39<35:35, 22.24s/it]Generation:   5%|▌         | 5/100 [02:05<37:02, 23.39s/it]Generation:   6%|▌         | 6/100 [02:27<36:09, 23.08s/it]Generation:   7%|▋         | 7/100 [02:46<33:43, 21.76s/it]Generation:   8%|▊         | 8/100 [03:15<37:00, 24.14s/it]Generation:   9%|▉         | 9/100 [03:40<36:49, 24.28s/it]Generation:  10%|█         | 10/100 [04:09<38:41, 25.79s/it]Generation:  11%|█         | 11/100 [04:39<40:16, 27.15s/it]Generation:  12%|█▏        | 12/100 [05:08<40:29, 27.61s/it]Generation:  13%|█▎        | 13/100 [05:36<40:14, 27.76s/it]Generation:  14%|█▍        | 14/100 [06:22<47:39, 33.25s/it]Generation:  15%|█▌        | 15/100 [06:55<46:48, 33.04s/it]Generation:  16%|█▌        | 16/100 [07:25<45:01, 32.16s/it]Generation:  17%|█▋        | 17/100 [07:56<44:12, 31.96s/it]Generation:  18%|█▊        | 18/100 [08:26<42:39, 31.21s/it]Generation:  19%|█▉        | 19/100 [08:52<39:59, 29.63s/it]Generation:  20%|██        | 20/100 [09:13<36:22, 27.28s/it]Generation:  21%|██        | 21/100 [09:42<36:13, 27.52s/it]Generation:  22%|██▏       | 22/100 [10:04<33:47, 26.00s/it]Generation:  23%|██▎       | 23/100 [10:31<33:56, 26.45s/it]Generation:  24%|██▍       | 24/100 [11:00<34:06, 26.93s/it]Generation:  25%|██▌       | 25/100 [11:33<36:07, 28.90s/it]Generation:  26%|██▌       | 26/100 [12:06<37:18, 30.25s/it]Generation:  27%|██▋       | 27/100 [12:45<39:52, 32.77s/it]Generation:  28%|██▊       | 28/100 [13:18<39:20, 32.78s/it]Generation:  29%|██▉       | 29/100 [13:47<37:21, 31.56s/it]Generation:  30%|███       | 30/100 [14:15<35:49, 30.71s/it]Generation:  31%|███       | 31/100 [14:55<38:27, 33.43s/it]Generation:  32%|███▏      | 32/100 [15:28<37:50, 33.39s/it]Generation:  33%|███▎      | 33/100 [16:00<36:37, 32.80s/it]Generation:  34%|███▍      | 34/100 [16:37<37:30, 34.10s/it]Generation:  35%|███▌      | 35/100 [17:07<35:35, 32.86s/it]Generation:  36%|███▌      | 36/100 [18:38<53:42, 50.36s/it]Generation:  37%|███▋      | 37/100 [19:17<49:23, 47.04s/it]Generation:  38%|███▊      | 38/100 [19:49<43:51, 42.44s/it]Generation:  39%|███▉      | 39/100 [20:29<42:27, 41.76s/it]Generation:  40%|████      | 40/100 [21:03<39:18, 39.31s/it]Generation:  41%|████      | 41/100 [21:42<38:28, 39.13s/it]Generation:  42%|████▏     | 42/100 [22:11<35:07, 36.34s/it]Generation:  43%|████▎     | 43/100 [22:42<32:48, 34.53s/it]Generation:  44%|████▍     | 44/100 [23:20<33:16, 35.65s/it]Generation:  45%|████▌     | 45/100 [23:54<32:11, 35.12s/it]Generation:  46%|████▌     | 46/100 [24:32<32:26, 36.04s/it]Generation:  47%|████▋     | 47/100 [25:35<38:53, 44.03s/it]Generation:  48%|████▊     | 48/100 [26:14<36:48, 42.47s/it]Generation:  49%|████▉     | 49/100 [26:48<34:03, 40.08s/it]Generation:  50%|█████     | 50/100 [27:15<30:12, 36.24s/it]Generation:  51%|█████     | 51/100 [28:42<41:52, 51.27s/it]Generation:  52%|█████▏    | 52/100 [29:09<35:13, 44.03s/it]Generation:  53%|█████▎    | 53/100 [29:46<32:53, 41.98s/it]Generation:  54%|█████▍    | 54/100 [30:11<28:21, 37.00s/it]Generation:  55%|█████▌    | 55/100 [30:38<25:30, 34.01s/it]Generation:  56%|█████▌    | 56/100 [31:21<26:47, 36.54s/it]Generation:  57%|█████▋    | 57/100 [31:51<24:48, 34.61s/it]Generation:  58%|█████▊    | 58/100 [32:32<25:33, 36.51s/it]Generation:  59%|█████▉    | 59/100 [33:17<26:38, 38.98s/it]Generation:  60%|██████    | 60/100 [33:47<24:19, 36.48s/it]Generation:  61%|██████    | 61/100 [34:23<23:37, 36.36s/it]Generation:  62%|██████▏   | 62/100 [35:06<24:13, 38.24s/it]Generation:  63%|██████▎   | 63/100 [35:36<22:00, 35.69s/it]Generation:  64%|██████▍   | 64/100 [36:17<22:28, 37.47s/it]Generation:  65%|██████▌   | 65/100 [36:49<20:53, 35.83s/it]Generation:  66%|██████▌   | 66/100 [37:36<22:07, 39.04s/it]Generation:  67%|██████▋   | 67/100 [38:08<20:23, 37.07s/it]Generation:  68%|██████▊   | 68/100 [38:41<19:06, 35.84s/it]Generation:  69%|██████▉   | 69/100 [39:31<20:36, 39.88s/it]Generation:  70%|███████   | 70/100 [40:07<19:24, 38.83s/it]Generation:  71%|███████   | 71/100 [40:39<17:44, 36.70s/it]Generation:  72%|███████▏  | 72/100 [41:28<18:54, 40.51s/it]Generation:  73%|███████▎  | 73/100 [42:02<17:19, 38.51s/it]Generation:  74%|███████▍  | 74/100 [43:10<20:29, 47.27s/it]Generation:  75%|███████▌  | 75/100 [43:41<17:45, 42.61s/it]Generation:  76%|███████▌  | 76/100 [44:31<17:49, 44.55s/it]Generation:  77%|███████▋  | 77/100 [45:04<15:46, 41.15s/it]Generation:  78%|███████▊  | 78/100 [45:38<14:19, 39.05s/it]Generation:  79%|███████▉  | 79/100 [46:14<13:21, 38.14s/it]Generation:  80%|████████  | 80/100 [47:06<14:04, 42.25s/it]Generation:  81%|████████  | 81/100 [47:40<12:35, 39.75s/it]Generation:  82%|████████▏ | 82/100 [48:11<11:09, 37.20s/it]Generation:  83%|████████▎ | 83/100 [49:02<11:44, 41.44s/it]Generation:  84%|████████▍ | 84/100 [49:41<10:48, 40.55s/it]Generation:  85%|████████▌ | 85/100 [50:32<10:56, 43.76s/it]Generation:  86%|████████▌ | 86/100 [51:03<09:20, 40.02s/it]Generation:  87%|████████▋ | 87/100 [52:38<12:13, 56.45s/it]Generation:  88%|████████▊ | 88/100 [53:11<09:52, 49.35s/it]Generation:  89%|████████▉ | 89/100 [53:42<08:04, 44.05s/it]Generation:  90%|█████████ | 90/100 [54:13<06:38, 39.87s/it]Generation:  91%|█████████ | 91/100 [54:42<05:31, 36.82s/it]Generation:  92%|█████████▏| 92/100 [55:39<05:43, 42.88s/it]Generation:  93%|█████████▎| 93/100 [56:09<04:32, 38.95s/it]Generation:  94%|█████████▍| 94/100 [56:38<03:35, 36.00s/it]Generation:  95%|█████████▌| 95/100 [57:11<02:55, 35.16s/it]Generation:  96%|█████████▌| 96/100 [57:41<02:13, 33.44s/it]Generation:  97%|█████████▋| 97/100 [58:10<01:36, 32.13s/it]Generation:  98%|█████████▊| 98/100 [59:03<01:16, 38.28s/it]Generation:  99%|█████████▉| 99/100 [59:32<00:35, 35.63s/it]Generation: 100%|██████████| 100/100 [1:00:04<00:00, 34.43s/it]Generation: 100%|██████████| 100/100 [1:00:04<00:00, 36.04s/it]
  0%|          | 0/100 [00:00<?, ?it/s]Generation:   0%|          | 0/100 [00:00<?, ?it/s]Generation:   1%|          | 1/100 [00:19<32:43, 19.83s/it]Generation:   2%|▏         | 2/100 [00:39<31:52, 19.51s/it]Generation:   3%|▎         | 3/100 [00:55<29:13, 18.07s/it]Generation:   4%|▍         | 4/100 [01:13<29:11, 18.25s/it]Generation:   5%|▌         | 5/100 [01:29<27:09, 17.15s/it]Generation:   6%|▌         | 6/100 [02:17<43:12, 27.58s/it]Generation:   7%|▋         | 7/100 [02:40<40:28, 26.11s/it]Generation:   8%|▊         | 8/100 [03:01<37:33, 24.49s/it]Generation:   9%|▉         | 9/100 [03:27<38:10, 25.17s/it]Generation:  10%|█         | 10/100 [03:51<37:06, 24.74s/it]Generation:  11%|█         | 11/100 [04:14<35:45, 24.10s/it]Generation:  12%|█▏        | 12/100 [05:06<48:05, 32.79s/it]Generation:  13%|█▎        | 13/100 [05:30<43:35, 30.07s/it]Generation:  14%|█▍        | 14/100 [05:55<40:47, 28.46s/it]Generation:  15%|█▌        | 15/100 [06:34<44:53, 31.69s/it]Generation:  16%|█▌        | 16/100 [06:58<40:59, 29.28s/it]Generation:  17%|█▋        | 17/100 [07:26<40:13, 29.08s/it]Generation:  18%|█▊        | 18/100 [08:06<44:08, 32.30s/it]Generation:  19%|█▉        | 19/100 [09:14<57:52, 42.86s/it]Generation:  20%|██        | 20/100 [09:54<56:17, 42.22s/it]Generation:  21%|██        | 21/100 [10:22<49:59, 37.96s/it]Generation:  22%|██▏       | 22/100 [10:49<44:48, 34.47s/it]Generation:  23%|██▎       | 23/100 [11:31<47:07, 36.72s/it]Generation:  24%|██▍       | 24/100 [11:58<43:00, 33.95s/it]Generation:  25%|██▌       | 25/100 [12:41<45:49, 36.66s/it]Generation:  26%|██▌       | 26/100 [13:25<47:42, 38.68s/it]Generation:  27%|██▋       | 27/100 [13:53<43:17, 35.59s/it]Generation:  28%|██▊       | 28/100 [14:33<44:18, 36.92s/it]Generation:  29%|██▉       | 29/100 [15:20<47:11, 39.88s/it]Generation:  30%|███       | 30/100 [15:47<41:57, 35.96s/it]Generation:  31%|███       | 31/100 [16:14<38:30, 33.49s/it]Generation:  32%|███▏      | 32/100 [17:30<52:07, 46.00s/it]Generation:  33%|███▎      | 33/100 [18:00<46:17, 41.46s/it]Generation:  34%|███▍      | 34/100 [19:06<53:32, 48.67s/it]Generation:  35%|███▌      | 35/100 [19:32<45:21, 41.87s/it]Generation:  36%|███▌      | 36/100 [20:23<47:36, 44.63s/it]Generation:  37%|███▋      | 37/100 [21:22<51:27, 49.01s/it]Generation:  38%|███▊      | 38/100 [21:49<43:52, 42.45s/it]Generation:  39%|███▉      | 39/100 [22:40<45:38, 44.90s/it]Generation:  40%|████      | 40/100 [23:12<41:04, 41.08s/it]Generation:  41%|████      | 41/100 [23:42<37:04, 37.71s/it]Generation:  42%|████▏     | 42/100 [24:35<41:00, 42.43s/it]Generation:  43%|████▎     | 43/100 [25:06<36:51, 38.80s/it]Generation:  44%|████▍     | 44/100 [25:41<35:16, 37.79s/it]Generation:  45%|████▌     | 45/100 [26:39<40:01, 43.67s/it]Generation:  46%|████▌     | 46/100 [27:09<35:39, 39.63s/it]Generation:  47%|████▋     | 47/100 [27:40<32:53, 37.23s/it]Generation:  48%|████▊     | 48/100 [28:27<34:45, 40.10s/it]Generation:  49%|████▉     | 49/100 [29:24<38:26, 45.23s/it]Generation:  50%|█████     | 50/100 [30:16<39:10, 47.01s/it]Generation:  51%|█████     | 51/100 [30:47<34:29, 42.24s/it]Generation:  52%|█████▏    | 52/100 [31:46<37:53, 47.36s/it]Generation:  53%|█████▎    | 53/100 [32:15<32:46, 41.84s/it]Generation:  54%|█████▍    | 54/100 [32:47<29:54, 39.02s/it]Generation:  55%|█████▌    | 55/100 [33:14<26:28, 35.29s/it]Generation:  56%|█████▌    | 56/100 [34:11<30:34, 41.70s/it]Generation:  57%|█████▋    | 57/100 [34:38<26:50, 37.46s/it]Generation:  58%|█████▊    | 58/100 [35:08<24:33, 35.08s/it]Generation:  59%|█████▉    | 59/100 [35:35<22:27, 32.87s/it]Generation:  60%|██████    | 60/100 [36:05<21:19, 31.99s/it]Generation:  61%|██████    | 61/100 [37:04<25:59, 39.98s/it]Generation:  62%|██████▏   | 62/100 [37:32<23:02, 36.38s/it]Generation:  63%|██████▎   | 63/100 [38:02<21:19, 34.58s/it]Generation:  64%|██████▍   | 64/100 [38:32<19:49, 33.05s/it]Generation:  65%|██████▌   | 65/100 [39:33<24:11, 41.46s/it]Generation:  66%|██████▌   | 66/100 [40:03<21:35, 38.09s/it]Generation:  67%|██████▋   | 67/100 [41:24<28:00, 50.93s/it]Generation:  68%|██████▊   | 68/100 [41:53<23:36, 44.28s/it]Generation:  69%|██████▉   | 69/100 [42:54<25:25, 49.22s/it]Generation:  70%|███████   | 70/100 [43:23<21:35, 43.20s/it]Generation:  71%|███████   | 71/100 [44:04<20:37, 42.68s/it]Generation:  72%|███████▏  | 72/100 [44:33<17:58, 38.52s/it]Generation:  73%|███████▎  | 73/100 [45:02<16:06, 35.80s/it]Generation:  74%|███████▍  | 74/100 [46:15<20:17, 46.83s/it]Generation:  75%|███████▌  | 75/100 [47:07<20:08, 48.35s/it]Generation:  76%|███████▌  | 76/100 [47:42<17:42, 44.25s/it]Generation:  77%|███████▋  | 77/100 [48:11<15:13, 39.72s/it]Generation:  78%|███████▊  | 78/100 [49:19<17:41, 48.24s/it]Generation:  79%|███████▉  | 79/100 [49:49<15:01, 42.95s/it]Generation:  80%|████████  | 80/100 [50:19<12:58, 38.93s/it]Generation:  81%|████████  | 81/100 [50:47<11:19, 35.77s/it]Generation:  82%|████████▏ | 82/100 [51:19<10:20, 34.45s/it]Generation:  83%|████████▎ | 83/100 [52:28<12:45, 45.03s/it]Generation:  84%|████████▍ | 84/100 [52:59<10:50, 40.67s/it]Generation:  85%|████████▌ | 85/100 [53:32<09:36, 38.42s/it]Generation:  86%|████████▌ | 86/100 [54:15<09:16, 39.78s/it]Generation:  87%|████████▋ | 87/100 [54:49<08:12, 37.87s/it]Generation:  88%|████████▊ | 88/100 [56:02<09:42, 48.57s/it]Generation:  89%|████████▉ | 89/100 [56:36<08:05, 44.14s/it]Generation:  90%|█████████ | 90/100 [57:07<06:42, 40.25s/it]Generation:  91%|█████████ | 91/100 [57:49<06:07, 40.86s/it]Generation:  92%|█████████▏| 92/100 [58:21<05:03, 37.98s/it]Generation:  93%|█████████▎| 93/100 [59:34<05:41, 48.72s/it]Generation:  94%|█████████▍| 94/100 [1:00:07<04:22, 43.82s/it]Generation:  95%|█████████▌| 95/100 [1:00:41<03:24, 40.95s/it]Generation:  96%|█████████▌| 96/100 [1:01:15<02:35, 38.80s/it]Generation:  97%|█████████▋| 97/100 [1:02:17<02:17, 45.79s/it]Generation:  98%|█████████▊| 98/100 [1:03:33<01:49, 54.85s/it]Generation:  99%|█████████▉| 99/100 [1:04:29<00:55, 55.39s/it]Generation: 100%|██████████| 100/100 [1:05:01<00:00, 48.24s/it]Generation: 100%|██████████| 100/100 [1:05:01<00:00, 39.02s/it]
  0%|          | 0/100 [00:00<?, ?it/s]Generation:   0%|          | 0/100 [00:00<?, ?it/s]Generation:   1%|          | 1/100 [00:41<1:08:37, 41.59s/it]Generation:   2%|▏         | 2/100 [02:32<2:14:12, 82.17s/it]Generation:   3%|▎         | 3/100 [03:57<2:15:19, 83.71s/it]Generation:   4%|▍         | 4/100 [05:56<2:35:52, 97.43s/it]Generation:   5%|▌         | 5/100 [07:29<2:31:56, 95.96s/it]Generation:   6%|▌         | 6/100 [08:43<2:18:25, 88.36s/it]Generation:   7%|▋         | 7/100 [12:02<3:13:05, 124.58s/it]Generation:   8%|▊         | 8/100 [13:10<2:43:33, 106.67s/it]Generation:   9%|▉         | 9/100 [14:30<2:28:51, 98.15s/it] Generation:  10%|█         | 10/100 [16:54<2:48:33, 112.37s/it]Generation:  11%|█         | 11/100 [19:13<2:58:54, 120.61s/it]Generation:  12%|█▏        | 12/100 [20:28<2:36:20, 106.60s/it]Generation:  13%|█▎        | 13/100 [25:31<4:01:06, 166.28s/it]Generation:  14%|█▍        | 14/100 [27:38<3:41:18, 154.40s/it]Generation:  15%|█▌        | 15/100 [29:48<3:28:03, 146.87s/it]Generation:  16%|█▌        | 16/100 [32:43<3:37:30, 155.36s/it]Generation:  17%|█▋        | 17/100 [34:17<3:09:43, 137.15s/it]Generation:  18%|█▊        | 18/100 [37:48<3:37:39, 159.26s/it]Generation:  19%|█▉        | 19/100 [39:29<3:11:13, 141.65s/it]Generation:  20%|██        | 20/100 [40:28<2:35:59, 117.00s/it]Generation:  21%|██        | 21/100 [45:37<3:49:39, 174.43s/it]Generation:  22%|██▏       | 22/100 [48:34<3:47:47, 175.22s/it]Generation:  23%|██▎       | 23/100 [56:10<5:33:08, 259.59s/it]Generation:  24%|██▍       | 24/100 [57:20<4:16:49, 202.75s/it]Generation:  25%|██▌       | 25/100 [1:02:52<5:01:51, 241.48s/it]Generation:  26%|██▌       | 26/100 [1:09:34<5:57:15, 289.67s/it]Generation:  27%|██▋       | 27/100 [1:15:04<6:07:05, 301.72s/it]Generation:  28%|██▊       | 28/100 [1:19:06<5:40:42, 283.92s/it]Generation:  29%|██▉       | 29/100 [1:21:47<4:52:14, 246.96s/it]Generation:  30%|███       | 30/100 [1:27:40<5:25:04, 278.64s/it]Generation:  31%|███       | 31/100 [1:30:11<4:36:20, 240.30s/it]Generation:  32%|███▏      | 32/100 [1:36:59<5:29:39, 290.88s/it]Generation:  33%|███▎      | 33/100 [1:39:12<4:31:42, 243.32s/it]Generation:  34%|███▍      | 34/100 [1:41:34<3:54:19, 213.02s/it]Generation:  35%|███▌      | 35/100 [1:45:29<3:57:53, 219.59s/it]Generation:  36%|███▌      | 36/100 [1:47:05<3:14:35, 182.42s/it]Generation:  37%|███▋      | 37/100 [1:48:27<2:39:56, 152.33s/it]Generation:  38%|███▊      | 38/100 [1:54:09<3:36:20, 209.36s/it]Generation:  39%|███▉      | 39/100 [1:56:38<3:14:29, 191.30s/it]Generation:  40%|████      | 40/100 [2:00:05<3:15:49, 195.82s/it]Generation:  41%|████      | 41/100 [2:10:34<5:20:29, 325.92s/it]Generation:  42%|████▏     | 42/100 [2:12:13<4:09:02, 257.63s/it]Generation:  43%|████▎     | 43/100 [2:18:19<4:35:43, 290.23s/it]Generation:  44%|████▍     | 44/100 [2:19:49<3:34:56, 230.29s/it]Generation:  45%|████▌     | 45/100 [2:23:43<3:31:53, 231.16s/it]Generation:  46%|████▌     | 46/100 [2:25:13<2:50:09, 189.07s/it]Generation:  47%|████▋     | 47/100 [2:28:05<2:42:28, 183.94s/it]Generation:  48%|████▊     | 48/100 [2:33:38<3:18:00, 228.48s/it]Generation:  49%|████▉     | 49/100 [2:40:51<4:06:25, 289.91s/it]Generation:  50%|█████     | 50/100 [2:49:09<4:53:33, 352.26s/it]Generation:  51%|█████     | 51/100 [2:59:36<5:55:10, 434.90s/it]Generation:  52%|█████▏    | 52/100 [3:01:33<4:31:35, 339.49s/it]Generation:  53%|█████▎    | 53/100 [3:09:30<4:58:08, 380.60s/it]Generation:  54%|█████▍    | 54/100 [3:12:41<4:08:09, 323.68s/it]Generation:  55%|█████▌    | 55/100 [3:19:33<4:22:37, 350.16s/it]Generation:  56%|█████▌    | 56/100 [3:30:20<5:22:12, 439.38s/it]Generation:  57%|█████▋    | 57/100 [3:34:05<4:28:46, 375.03s/it]Generation:  58%|█████▊    | 58/100 [3:37:49<3:50:52, 329.81s/it]Generation:  59%|█████▉    | 59/100 [3:52:51<5:42:33, 501.32s/it]Generation:  60%|██████    | 60/100 [3:56:48<4:41:21, 422.03s/it]Generation:  61%|██████    | 61/100 [3:59:17<3:41:09, 340.24s/it]Generation:  62%|██████▏   | 62/100 [4:03:15<3:15:58, 309.44s/it]Generation:  63%|██████▎   | 63/100 [4:06:37<2:50:56, 277.20s/it]Generation:  64%|██████▍   | 64/100 [4:10:36<2:39:32, 265.90s/it]Generation:  65%|██████▌   | 65/100 [4:13:47<2:21:58, 243.38s/it]Generation:  66%|██████▌   | 66/100 [4:20:48<2:48:02, 296.55s/it]Generation:  67%|██████▋   | 67/100 [4:28:11<3:07:21, 340.64s/it]Generation:  68%|██████▊   | 68/100 [4:33:22<2:56:57, 331.78s/it]Generation:  69%|██████▉   | 69/100 [4:38:46<2:50:06, 329.23s/it]Generation:  70%|███████   | 70/100 [4:41:46<2:22:18, 284.62s/it]Generation:  71%|███████   | 71/100 [4:54:05<3:23:26, 420.90s/it]Generation:  72%|███████▏  | 72/100 [5:02:18<3:26:30, 442.51s/it]Generation:  73%|███████▎  | 73/100 [5:12:04<3:38:28, 485.51s/it]Generation:  74%|███████▍  | 74/100 [5:19:44<3:27:01, 477.74s/it]Generation:  75%|███████▌  | 75/100 [5:22:14<2:38:05, 379.41s/it]Generation:  76%|███████▌  | 76/100 [5:32:19<2:58:49, 447.07s/it]Generation:  77%|███████▋  | 77/100 [5:35:08<2:19:27, 363.79s/it]Generation:  78%|███████▊  | 78/100 [5:37:06<1:46:22, 290.10s/it]Generation:  79%|███████▉  | 79/100 [5:40:35<1:33:02, 265.83s/it]Generation:  80%|████████  | 80/100 [5:42:49<1:15:26, 226.32s/it]Generation:  81%|████████  | 81/100 [5:50:34<1:34:15, 297.66s/it]Generation:  82%|████████▏ | 82/100 [5:52:49<1:14:42, 249.03s/it]Generation:  83%|████████▎ | 83/100 [6:00:39<1:29:18, 315.21s/it]Generation:  84%|████████▍ | 84/100 [6:02:48<1:09:11, 259.46s/it]Generation:  85%|████████▌ | 85/100 [6:06:00<59:49, 239.30s/it]  2025-09-06 05:42:40,414 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:40,421 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:40,489 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write [{'op': 'key-in-memory', 'key': 'eval_objective_list-0eddd216be74cf77a6fa0a447a1afb0c', 'type': b'\x80\x05\x95\x15\x00\x00\x00\x00\x00\x00\x00\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94.'}]
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 6269, in send_all
    c.send(*msgs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:40,491 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:40,491 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:41,108 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:41,109 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:41,464 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:41,464 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
Cancelled future (likely memory related)
2025-09-06 05:42:42,004 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:42,004 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:42,606 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:42,606 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:43,467 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:43,468 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:43,502 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
2025-09-06 05:42:43,502 - distributed.scheduler - CRITICAL - Closed comm <BatchedSend: closed> while trying to write {'op': 'key-in-memory', 'key': 'ndarray-31f753c01c747713373888511ad49a92'}
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5862, in report
    c.send(msg)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/batched.py", line 156, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Scheduler->Client local=tcp://127.0.0.1:41069 remote=tcp://127.0.0.1:51624> already closed.
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25930211' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25939648' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  86%|████████▌ | 86/100 [6:08:30<49:35, 212.53s/it]Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25947347' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25950022' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  87%|████████▋ | 87/100 [6:09:33<36:16, 167.39s/it]Task exception was never retrieved
future: <Task finished name='Task-25958304' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25967002' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25975133' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  88%|████████▊ | 88/100 [6:10:35<27:10, 135.87s/it]Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25982765' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-25985094' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  89%|████████▉ | 89/100 [6:11:35<20:45, 113.24s/it]Task exception was never retrieved
future: <Task finished name='Task-25993344' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26002604' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  90%|█████████ | 90/100 [6:14:08<20:50, 125.04s/it]Task exception was never retrieved
future: <Task finished name='Task-26011159' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26020351' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26028326' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  91%|█████████ | 91/100 [6:15:08<15:49, 105.51s/it]Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26035459' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26038390' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  92%|█████████▏| 92/100 [6:16:09<12:18, 92.28s/it] Task exception was never retrieved
future: <Task finished name='Task-26046312' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26055494' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  93%|█████████▎| 93/100 [6:17:10<09:38, 82.70s/it]Task exception was never retrieved
future: <Task finished name='Task-26063265' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26072724' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26080237' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  94%|█████████▍| 94/100 [6:18:11<07:38, 76.37s/it]Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26089339' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26090802' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  95%|█████████▌| 95/100 [6:20:47<08:21, 100.21s/it]Task exception was never retrieved
future: <Task finished name='Task-26098382' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26107491' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26114688' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  96%|█████████▌| 96/100 [6:21:48<05:53, 88.37s/it] Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26121361' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26124235' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  97%|█████████▋| 97/100 [6:22:50<04:01, 80.61s/it]Task exception was never retrieved
future: <Task finished name='Task-26131522' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26140106' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26147188' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  98%|█████████▊| 98/100 [6:23:50<02:28, 74.30s/it]Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26154192' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26156446' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation:  99%|█████████▉| 99/100 [6:26:31<01:40, 100.35s/it]Task exception was never retrieved
future: <Task finished name='Task-26164027' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Task exception was never retrieved
future: <Task finished name='Task-26172953' coro=<Server._handle_comm() done, defined at /home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py:737> exception=AssertionError(<TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>)>
Traceback (most recent call last):
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 831, in _handle_comm
    result = await result
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 5904, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/core.py", line 912, in handle_stream
    await handler(**merge(extra, msg))
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/utils.py", line 837, in wrapper
    return await func(*args, **kwargs)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4893, in update_graph
    self._create_taskstate_from_graph(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 4831, in _create_taskstate_from_graph
    self.transitions(recommendations, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 8181, in transitions
    self._transitions(recommendations, client_msgs, worker_msgs, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2134, in _transitions
    new_recs, new_cmsgs, new_wmsgs = self._transition(key, finish, stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2017, in _transition
    recommendations, client_msgs, worker_msgs = func(
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 2468, in _transition_waiting_processing
    return self._add_to_processing(ts, ws, stimulus_id=stimulus_id)
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3415, in _add_to_processing
    return {}, {}, {ws.address: [self._task_to_msg(ts)]}
  File "/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/distributed/scheduler.py", line 3587, in _task_to_msg
    assert ts.priority, ts
AssertionError: <TaskState 'ndarray-1f14e8bfa35c6f483a20d11ba4fbbaa1' forgotten>
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Cancelled future (likely memory related)
Generation: 100%|██████████| 100/100 [6:27:30<00:00, 88.06s/it]Generation: 100%|██████████| 100/100 [6:27:30<00:00, 232.51s/it]
/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(
0it [00:00, ?it/s]Generation: : 0it [00:00, ?it/s]Generation: : 1it [59:09, 3549.66s/it]Generation: : 1it [59:09, 3549.78s/it]
DONE
